---
title: Capture plant health with NDVI and Raspberry Pi
hero_image: images/banner.png
description: Use a Raspberry Pi and camera to measure the health of plants using infrared
  light.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
  completion: engaged
- title: What is NDVI?
- title: Load and display images with Python
- title: Increasing the contrast
- title: Calculating NDVI
- title: Colour mapping
- title: Create your own NDVI images
  completion: internal
- title: Mission Space Lab
#- title: What next?
